version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.12

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew

      - run: ./gradlew clean build

      - store_test_results:
          path: build/test-results

      - store_artifacts:
          path: build/reports/tests/test
          destination: test_result

      - store_artifacts:
          path: build/reports/pmd
          destination: pmd

      - store_artifacts:
          path: build/reports/checkstyle
          destination: checkstyle

      - store_artifacts:
          path: build/reports/spotbugs
          destination: spotbugs
          
      - store_artifacts:
          path: build/reports/sonarlint
          destination: sonarlint        
