    name: GitHub Classroom Workflow

    on: [push]

    jobs:
        build:
            name: Check Code Quality
            runs-on: ubuntu-latest
            steps:
            - name: Check-out Repository
              uses: actions/checkout@v2
            - name: Setup Java 11
              uses: actions/setup-java@v1
              with:
                    java-version: '11'
            - name: Testing (Checkstyle, JUnit, ...)
              uses: education/autograding@v1
            - name: Checkstyle file existence
              id: checkstyle_files
              uses: andstor/file-existence-action@v1
              with:
                    files: "build/reports/checkstyle/main.html"
            - name: Create Artifact for Checkstyle
              uses: actions/upload-artifact@v3
              if: steps.checkstyle_files.outputs.files_exists == 'true'
              with:
                    name: Checkstyle
                    path: build/reports/checkstyle
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                    name: Sonarlint
                    path: build/reports/sonarlint
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                    name: Spotbugs
                    path: build/reports/spotbugs
            - name: JUnit file existence
              id: checkjunit_files
              uses: andstor/file-existence-action@v1
              with:
                    files: "build/reports/tests/test/index.html"
            - name: Create Artifact for Checkstyle
              uses: actions/upload-artifact@v3
              if: steps.checkjunit_files.outputs.files_exists == 'true'
              with:
                    name: JUnit
                    path: build/reports/tests
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                    name: PMD
                    path: build/reports/pmd
