    name: GitHub Classroom Workflow

    on: [push]

    jobs:
        build:
            name: Check Code Quality
            runs-on: ubuntu-latest
            steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v1
              with:
                    java-version: '11'
            - uses: education/autograding@v1
            - name: Checkstyle file existence
              id: checkstyle_files
              uses: andstor/file-existence-action@v1
              with:
                    files: "build/reports/checkstyle/main.html"
            - uses: actions/upload-artifact@v3
              if: steps.checkstyle_files.outputs.files_exists == 'true'
              with:
                    name: Checkstyle
                    path: build/reports/checkstyle
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                    name: Sonarlint
                    path: build/reports/sonarlint
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                    name: Spotbugs
                    path: build/reports/spotbugs
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                    name: JUnit
                    path: build/reports/tests
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                    name: PMD
                    path: build/reports/pmd
