    name: GitHub Classroom Workflow

    on: [push]

    jobs:
        build:
            name: Check Code Quality
            runs-on: ubuntu-latest
            steps:
            - name: Check-out Repository
              uses: actions/checkout@v2
            - name: Setup Java 11
              uses: actions/setup-java@v1
              with:
                    java-version: '11'
            - name: Testing (Checkstyle, JUnit, ...)
              uses: education/autograding@v1
            - name: Checkstyle file existence
              id: checkstyle_files
              uses: andstor/file-existence-action@v1
              with:
                    files: "build/reports/checkstyle/main.html"
            - name: Create Artifact for Checkstyle
              uses: actions/upload-artifact@v3
              if: steps.checkstyle_files.outputs.files_exists == 'true'
              with:
                    name: Checkstyle
                    path: build/reports/checkstyle
            - name: Sonarlint file existence
              id: checksonarlint_files
              uses: andstor/file-existence-action@v1
              with:
                    files: "build/reports/sonarlint/sonarlintMain/report.html"        
            - name: Create Artifact for Sonarlint
              uses: actions/upload-artifact@v3
              if: steps.checksonarlint_files.outputs.files_exists == 'true'
              with:
                    name: Sonarlint
                    path: build/reports/sonarlint
            - name: Spotbugs file existence
              id: checkspotbugs_files
              uses: andstor/file-existence-action@v1
              with:
                    files: "build/reports/spotbugs/main.html"  
            - name: Create Artifact for Spotbugs
              uses: actions/upload-artifact@v3
              if: steps.checkspotbugs_files.outputs.files_exists == 'true'
              with:
                    name: Spotbugs
                    path: build/reports/spotbugs
            - name: JUnit file existence
              id: checkjunit_files
              uses: andstor/file-existence-action@v1
              with:
                    files: "build/reports/tests/test/index.html"
            - name: Create Artifact for JUnit
              uses: actions/upload-artifact@v3
              if: steps.checkjunit_files.outputs.files_exists == 'true'
              with:
                    name: JUnit
                    path: build/reports/tests
            - name: PMD file existence
              id: checkpmd_files
              uses: andstor/file-existence-action@v1
              with:
                    files: "build/reports/pmd/pmdMain/report.html" 
            - name: Create Artifact for PMD
              uses: actions/upload-artifact@v3
              if: steps.checkpmd_files.outputs.files_exists == 'true'
              with:
                    name: PMD
                    path: build/reports/pmd

            - name: Pushes test file
              uses: dmnemec/copy_file_to_another_repo_action@main
              env:
                    API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
              with:
                    source_file: 'build/reports/pmd/pmdMain/report.html'
                    destination_repo: 'alehmannFRA-UAS/OOP-Java-Adv'
                    user_email: '41898282+github-actions[bot]@users.noreply.github.com'
                    user_name: 'github-actions[bot]'
                    commit_message: 'A custom message for the commit'
